// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElCard: typeof import('element-plus/es')['ElCard'];
    ElCol: typeof import('element-plus/es')['ElCol'];
    ElContainer: typeof import('element-plus/es')['ElContainer'];
    ElImage: typeof import('element-plus/es')['ElImage'];
    ElMain: typeof import('element-plus/es')['ElMain'];
    ElRow: typeof import('element-plus/es')['ElRow'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default'];
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default'];
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default'];
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default'];
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SignIn: typeof import('./src/components/signup/SignIn.vue')['default'];
    SignUp: typeof import('./src/components/signup/SignUp.vue')['default'];
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default'];
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default'];
  }
}

export {};
