// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    GameDetail: typeof import('./components/game-detail/GameDetail.vue')['default']
    GameDetailInfo: typeof import('./components/game-detail/game-detail-info/GameDetailInfo.vue')['default']
    GameJournal: typeof import('./components/journal/GameJournal.vue')['default']
    GridGameItem: typeof import('./components/journal/grid-view/game-item/GridGameItem.vue')['default']
    GridGameList: typeof import('./components/journal/grid-view/game-list/GridGameList.vue')['default']
    GridView: typeof import('./components/journal/grid-view/GridView.vue')['default']
    HPagination: typeof import('./components/utility/HPagination.vue')['default']
    HSearchInput: typeof import('./components/search/HSearchInput.vue')['default']
    HSearchInputTemplate: typeof import('./components/search/search-input/HSearchInputTemplate.vue')['default']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignUp: typeof import('./components/signup/SignUp.vue')['default']
  }
}

export {}
